name: Make release and binaries

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --no-save --cwd ./beszel/site

      - name: Build site
        run: bun run --cwd ./beszel/site build

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.1'

      - name: GoReleaser beszel
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir: ./beszel
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          workdir: ./beszel
          name: my-executable # 这是你给这个构件起的名字
          path: ./dist/beszel-agent_windows_arm64.zip # 这是你的可执行文件的路径
